name: Node CI Social App

on:
  push

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - working-directory: ./front
      - run : /front/npm test
      - working-directory: ./front
      - run : /front/npm run build --if-present
      - working-directory: ./front
      - run: front/npm run deploy
