name: Node CI Social App

on:
  push

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: /front/npm ci
      - run : /front/npm test
      - run : /front/npm run build
      - run: front/npm run deploy
