name: Node CI Social App

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
        working-directory: ./front
      - run : /front/npm test --if-present
        working-directory: ./front
      - run : /front/npm run build --if-present
        working-directory: ./front
      - run: front/npm run deploy
